# Generated by Django 5.1.6 on 2025-02-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urbanchattelapp', '0002_property_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='profile_picture',
            new_name='property_image',
        ),
    ]
