# Generated by Django 5.1.6 on 2025-02-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanchattelapp', '0003_rename_profile_picture_property_property_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_image',
        ),
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='property/'),
        ),
    ]
