# Generated by Django 5.1.6 on 2025-02-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanchattelapp', '0004_remove_property_property_image_property_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='property',
            name='description',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
        migrations.AddField(
            model_name='property',
            name='configurations',
            field=models.CharField(default='2 BHK', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='flat_size_max',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='property',
            name='flat_size_min',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='property',
            name='price_max',
            field=models.DecimalField(decimal_places=2, default=10000000, max_digits=10),
        ),
        migrations.AddField(
            model_name='property',
            name='price_min',
            field=models.DecimalField(decimal_places=2, default=10000000, max_digits=10),
        ),
        migrations.AddField(
            model_name='property',
            name='project_size_acres',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='property',
            name='project_size_units',
            field=models.IntegerField(default=100),
        ),
    ]
