# Generated by Django 5.1.6 on 2025-03-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanchattelapp', '0005_rename_title_property_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='about',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='property',
            name='project_status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
