# Generated by Django 5.1.6 on 2025-03-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanchattelapp', '0006_property_about_property_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='Bulider',
            field=models.CharField(default='Unknown Builder', max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='loaclity',
            field=models.CharField(default='Unknown Locality', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='micro_makret',
            field=models.CharField(default='Unknown Market', max_length=200),
        ),
    ]
