# Generated by Django 5.1.6 on 2025-03-05 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urbanchattelapp', '0007_property_bulider_property_loaclity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='Bulider',
            new_name='builder',
        ),
    ]
