# Generated by Django 5.1.6 on 2025-03-05 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urbanchattelapp', '0008_rename_bulider_property_builder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='micro_makret',
            new_name='micro_market',
        ),
    ]
