# Generated by Django 5.1.6 on 2025-03-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanchattelapp', '0009_rename_micro_makret_property_micro_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='Basketball',
            field=models.CharField(default='not avilable', max_length=300),
        ),
        migrations.AddField(
            model_name='property',
            name='Volleyball',
            field=models.CharField(default='not avilable', max_length=300),
        ),
        migrations.AddField(
            model_name='property',
            name='badminton_court',
            field=models.CharField(default='not avilable', max_length=300),
        ),
        migrations.AddField(
            model_name='property',
            name='cricket',
            field=models.CharField(default='not avilable', max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='gymnasium',
            field=models.CharField(default='Not avilabe', max_length=300),
        ),
        migrations.AddField(
            model_name='property',
            name='jogging',
            field=models.CharField(default='not avilable', max_length=300),
        ),
        migrations.AddField(
            model_name='property',
            name='kid_play_areas',
            field=models.CharField(default='not avilable', max_length=300),
        ),
        migrations.AddField(
            model_name='property',
            name='kids_pool',
            field=models.CharField(default='not avilable', max_length=300),
        ),
        migrations.AddField(
            model_name='property',
            name='swimming_pool',
            field=models.CharField(default='Not avilabe', max_length=300),
        ),
        migrations.AddField(
            model_name='property',
            name='table_tennis',
            field=models.CharField(default='not avilable', max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='tennis_court',
            field=models.CharField(default='not avilable', max_length=300),
        ),
        migrations.AddField(
            model_name='property',
            name='yoga_areas',
            field=models.CharField(default='not avilable', max_length=300),
        ),
    ]
