# Generated by Django 5.1.6 on 2025-03-07 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urbanchattelapp', '0011_propertyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image',
        ),
    ]
