# Generated by Django 5.1.6 on 2025-03-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanchattelapp', '0013_alter_propertyimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='property/'),
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
    ]
