# Generated by Django 5.1.6 on 2025-03-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanchattelapp', '0016_property_image_delete_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='Guest_house',
            field=models.CharField(default='not avilable', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='Power_backup',
            field=models.CharField(default='not avilable', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='lift',
            field=models.CharField(default='not avilable', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='party_lawn',
            field=models.CharField(default='not avilable', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='treated_water_supply',
            field=models.CharField(default='not avilable', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='water_supply',
            field=models.CharField(default='not avilable', max_length=100),
        ),
    ]
